name: Codesniffer with the Magento Coding standard
on: push

jobs:
  build:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: actions/checkout@v4

      - name: Run codesniffer
        run: docker run
          --volume $(pwd)/:/app/workdir
          michielgerritsen/magento-coding-standard:latest
          --severity=6
