name: Lint PHP files
on: push

jobs:
  php-71:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: StephaneBour/actions-php-lint@7.1
        with:
          dir: "./"

  php-72:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: StephaneBour/actions-php-lint@7.2
        with:
          dir: "./"

  php-73:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: StephaneBour/actions-php-lint@7.3
        with:
          dir: "./"

  php-74:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: "./"

  php-80:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: StephaneBour/actions-php-lint@8.0
        with:
          dir: "./"

  php-81:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    steps:
      - uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: "./"
